export default [
  {
    col: { xs: 12, sm: 6, md: 6 },
    icon: "user",
    id: "nome-cartao",
    label: "Nome do Titular",
    type: "text",
    name: "creditcard_name",
    placeholder: "Nome do titular do Cartão",
  },
  {
    mask: "999.999.999-99",
    col: { xs: 12, sm: 6, md: 6 },
    icon: "contact",
    label: "CPF do Titular",
    type: "text",
    id: "cpf-cartao",
    name: "creditcard_cpf",
    placeholder: "Digite apenas números",
  },
  {
    mask: "99 99999 9999",
    showMask: false,
    col: { xs: 12, sm: 6, md: 6 },
    icon: "phone",
    id: "phone-cartao",
    label: "Número de Telefone",
    type: "tel",
    name: "creditcard_phone",
    placeholder: "Digite apenas números",
  },
  {
    col: { xs: 12, sm: 6, md: 6 },
    icon: "at",
    id: "email-cartao",
    label: "Email",
    name: "creditcard_email",
    type: "email",
    placeholder: "Ex.: exemplo@email.com",
  },
  {
    mask: "99",
    showMask: false,
    col: { xs: 6, sm: 3, md: 3 },
    icon: "caret-right",
    label: "Mês de Vencimento",
    type: "text",
    id: "mes-vencimento",
    name: "creditcard_expiration_month",
    placeholder: "ex: 02",
  },
  {
    mask: "9999",
    showMask: false,
    col: { xs: 6, sm: 3, md: 3 },
    icon: "caret-right",
    id: "ano-vencimento",
    label: "Ano de Vencimento",
    type: "text",
    name: "creditcard_expiration_year",
    placeholder: "ex: 2025",
  },
  {
    mask: "999",
    showMask: false,
    col: { xs: 12, sm: 6, md: 6 },
    icon: "caret-right",
    id: "cvv",
    label: "Código de Segurança",
    type: "text",
    name: "creditcard_cvv",
    placeholder: "Número de segurança atrás do cartão. Ex: '222'",
  },
];
