module.exports = {
  apps: [
    {
      name: "alcatra1",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n alcatra1 -O fair --queues local_priority,default ",
      watch: false,
      interpreter: "",
    },
    {
      name: "alcatra2",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n alcatra2 -O fair --queues local_priority ",
      watch: false,
      interpreter: "",
    },
    {
      name: "alcatra3",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n alcatra3 -O fair --queues short_running,long_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "alcatra4",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n alcatra4 -O fair --queues items_queue ",
      watch: false,
      interpreter: "",
    },
    {
      name: "alcatra5",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n alcatra5 -O fair --queues local_priority,short_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "alcatra6",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n alcatra6 -O fair --queues short_running,long_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "alcatra7",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n alcatra7 -O fair --queues short_running,long_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "alcatra8",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n alcatra8 -O fair --queues short_running,long_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "beat",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery -A workers.app beat ",
      watch: false,
      interpreter: "",
    },
  ],
};
