module.exports = {
  apps: [
    {
      name: "coxaomole1",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n coxaomole1 -O fair --queues local_priority ",
      watch: false,
      interpreter: "",
    },
    {
      name: "coxaomole2",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n coxaomole2 -O fair --queues long_running,short_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "coxaomole3",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n coxaomole3 -O fair --queues long_running,short_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "coxaomole4",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n coxaomole4 -O fair --queues long_running,short_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "coxaomole5",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n coxaomole5 -O fair --queues long_running,short_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "coxaomole6",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n coxaomole6 -O fair --queues long_running,short_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "coxaomole7",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n coxaomole7 -O fair --queues long_running,short_running ",
      watch: false,
      interpreter: "",
    },
    {
      name: "coxaomole8",
      cwd: ".",
      script: "venv/bin/python3",
      args: "-m celery --app=workers.app worker --loglevel=error --concurrency=7 -n coxaomole8 -O fair --queues long_running,short_running ",
      watch: false,
      interpreter: "",
    },
  ],
};
