from workers.tasks.admin.unblock_all_customers_from_account import unblock_all_customers_from_account
from workers.tasks.article_edit_sku import article_sku_edit_item
from workers.tasks.article_import import article_import_item, article_import_mercadolibre_many, article_import_shopee_many
from workers.tasks.notifications_process import generate_nfse
from workers.tasks.notifications_process import webhook_notification
from workers.tasks.notifications_process import notification_process_advertising
from workers.tasks.notifications_process import notification_process_catalog_competition
from workers.tasks.notifications_process import notification_process_nfse
from workers.tasks.notifications_process import notification_process_order
from workers.tasks.notifications_process import notification_process_order_message
from workers.tasks.notifications_process import notification_process_order_payment
from workers.tasks.notifications_process import notification_process_order_shipment
from workers.tasks.notifications_process import notification_process_payment_pjbank
from workers.tasks.notifications_process import notification_process_question
from workers.tasks.notifications_process import notification_process_mshops_item_price
from workers.tasks.stock_operations import decrease_stock, decrease_stock_mercadolibre, decrease_stock_shopee, increase_stock_mercadolibre, increase_stock_shopee
from workers.tasks.tag_items import tag_advertisings, tag_files, tag_item, untag_advertisings, untag_files, untag_item
from workers.tasks.vacation_mode import vacation_apply_tag, vacation_bihourly_check_start_pending, vacation_bihourly_check_end_pending, vacation_bihourly_check_start, vacation_bihourly_check_end, vacation_daily_check, vacation_mode_activate, vacation_mode_deactivate, vacation_remove_tag

from workers.tasks.mercadolibre.advertising_description_header_footer_add_item import advertising_description_add_header_footer_item
from workers.tasks.mercadolibre.advertising_description_header_footer_add_many import advertising_description_add_header_footer_many
from workers.tasks.mercadolibre.advertising_description_replace_text_item import advertising_description_replace_text_item
from workers.tasks.mercadolibre.advertising_description_replace_text_many import advertising_description_replace_text_many
from workers.tasks.mercadolibre.advertising_description_set_text_item import advertising_description_text_set_item
from workers.tasks.mercadolibre.advertising_description_set_text_many import advertising_description_text_set_many
from workers.tasks.mercadolibre.advertising_discount_item import discount_apply_item
from workers.tasks.mercadolibre.advertising_discount_item import discount_remove_item
from workers.tasks.mercadolibre.advertising_discount_many import discount_apply_many
from workers.tasks.mercadolibre.advertising_discount_many import discount_remove_many
from workers.tasks.mercadolibre.advertising_duplicate_item import advertising_duplicate_item
from workers.tasks.mercadolibre.advertising_duplicate_item import advertising_replicate_shopee_item
from workers.tasks.mercadolibre.advertising_duplicate_many import advertising_duplicate_many
from workers.tasks.mercadolibre.advertising_duplicate_many import advertising_duplicate_many_owned
from workers.tasks.mercadolibre.advertising_duplicate_many import advertising_replicate_shopee_many
from workers.tasks.mercadolibre.advertising_import_all import advertising_import_all, mshops_advertising_import_all
from workers.tasks.mercadolibre.advertising_import_all import enqueue_items, enqueue_mshops_items
from workers.tasks.mercadolibre.advertising_import_item import advertising_import_item
from workers.tasks.mercadolibre.advertising_import_item import mshops_advertising_import_item
from workers.tasks.mercadolibre.advertising_manufacturing_time_set_item import advertising_manufacturing_time_set_item
from workers.tasks.mercadolibre.advertising_manufacturing_time_set_many import advertising_manufacturing_time_set_many
from workers.tasks.mercadolibre.advertisings_position_finder import advertising_lookup_visits
from workers.tasks.mercadolibre.advertisings_position_finder import advertisings_position_finder
from workers.tasks.mercadolibre.advertisings_position_finder import find_category_advertisings_position
from workers.tasks.mercadolibre.advertisings_position_finder import visits_complete_history_lookup
from workers.tasks.mercadolibre.advertising_price_set_item import advertising_price_set_item
from workers.tasks.mercadolibre.advertising_price_set_many import advertising_price_set_batch_items
from workers.tasks.mercadolibre.advertising_price_set_many import advertising_price_set_many
from workers.tasks.mercadolibre.advertising_sku_edit import advertising_sku_set_many, advertising_sku_set_item
from workers.tasks.mercadolibre.advertising_stage_parsing import parse_advertising_json_all
from workers.tasks.mercadolibre.advertising_stage_parsing import parse_advertising_json_single_item
from workers.tasks.mercadolibre.advertising_status_item import advertising_status_set_item
from workers.tasks.mercadolibre.advertising_status_many import advertising_status_set_many
from workers.tasks.mercadolibre.blacklist_block_customer import blacklist_block_customer
from workers.tasks.mercadolibre.blacklist_block_customer import blacklist_block_customer_list
from workers.tasks.mercadolibre.blacklist_import_all import blacklist_import_all
from workers.tasks.mercadolibre.blacklist_list import blacklist_add_customer_list
from workers.tasks.mercadolibre.blacklist_mass_block_customers import blacklist_mass_block_customers
from workers.tasks.mercadolibre.blacklist_mass_update_customers_list import blacklist_mass_update_customers_list
from workers.tasks.mercadolibre.blacklist_unblock_customer import blacklist_unblock_customer
from workers.tasks.mercadolibre.blacklist_update_customer_list import blacklist_update_customer_list
from workers.tasks.mercadolibre.catalog_publishing import catalog_create_advertising
from workers.tasks.mercadolibre.catalog_publishing import catalog_publish_advertising
from workers.tasks.mercadolibre.catalog_publishing import catalog_publish_all
from workers.tasks.mercadolibre.catalog_publishing import catalog_publish_multiple_advertisings
from workers.tasks.mercadolibre.catalog_publishing import catalog_publish_new_advertising
from workers.tasks.mercadolibre.catalog_publishing import catalog_publish_variations
from workers.tasks.mercadolibre.catalog_publishing import catalog_replace_listing
from workers.tasks.mercadolibre.catalog_eligibility import catalog_evaluate_eligibility_set_item, catalog_evaluate_eligibility_set_many
from workers.tasks.mercadolibre.chart_advertisings import chart_advertisings_set_item, chart_advertisings_set_many
from workers.tasks.mercadolibre.order_import_all import order_import_all
from workers.tasks.mercadolibre.order_import_item import order_import_item
from workers.tasks.mercadolibre.order_stage_parsing import parse_order_json
from workers.tasks.mercadolibre.print_label import print_label_many
from workers.tasks.mercadolibre.promotions_apply import promotion_apply_many, promotion_apply_item
from workers.tasks.mercadolibre.promotions_import import promotions_import_all, promotions_import_item
from workers.tasks.mercadolibre.promotions_remove import promotion_remove_many, promotion_remove_item
from workers.tasks.mercadolibre.questions_tasks import fetch_account_question_number
from workers.tasks.mercadolibre.shipping_mercadoenvios_flex_set_item import shipping_mercadoenvios_flex_item
from workers.tasks.mercadolibre.shipping_mercadoenvios_flex_set_many import shipping_mercadoenvios_flex_many


from workers.tasks.shopee.duplicate_advertising_item import shopee_advertising_duplicate_item
from workers.tasks.shopee.duplicate_advertising_item import advertising_replicate_mercadolibre_item
from workers.tasks.shopee.duplicate_advertising_many import shopee_advertising_duplicate_many_owned
from workers.tasks.shopee.duplicate_advertising_many import advertising_replicate_mercadolibre_many
from workers.tasks.shopee.price_update import shopee_alter_price_batch, shopee_alter_price_many
from workers.tasks.shopee.description_update import shopee_alter_description_batch, shopee_alter_description_many
from workers.tasks.shopee.import_categories import shopee_import_categories
from workers.tasks.shopee.import_item_list import shopee_import_item_list
from workers.tasks.shopee.import_item import shopee_import_item
from workers.tasks.shopee.import_order_list import shopee_import_order_list, shopee_order_page_import
from workers.tasks.shopee.items_parsing import parse_shopee_items
from workers.tasks.shopee.orders_parsing import parse_shopee_orders
from workers.tasks.shopee.notifications_shopee_process import notification_process_shopee
