CREATE TABLE meuml.mshops_advertisings (
	id serial NOT NULL,
	external_id varchar(22) NOT NULL,
	account_id int8 NOT NULL,
	site_id bpchar(3) NOT NULL,
	category_id varchar(30) NOT NULL,
	title varchar(201) NOT NULL,
	status varchar(51) NOT NULL,
	domain_id varchar(100) NULL,
	catalog_product_id varchar(30) NULL,
	catalog_listing bool NOT NULL,
	currency_id bpchar(3) NOT NULL,
	price numeric(22, 2) NOT NULL,
	"condition" varchar(52) NOT NULL,
	initial_quantity int4 NOT NULL,
	available_quantity int4 NOT NULL,
	sold_quantity int4 NOT NULL,
	listing_type_id varchar(30) NOT NULL,
	free_shipping int2 NOT NULL,
	shipping_mode varchar(53) NOT NULL,
	buying_mode varchar(202) NULL,
	permalink varchar(300) NOT NULL,
	secure_thumbnail varchar(204) NOT NULL,
	tags varchar(205) NOT NULL,
	start_time timestamp NOT NULL,
	date_created timestamp NOT NULL,
	last_updated timestamp NULL,
	parent_item_id varchar(30) NULL,
	accepts_mercadopago bool NULL,
	warranty text NULL,
	total_listing_fee numeric(22, 2) NULL,
	catalog_status int2 NULL,
	quality float4 NULL,
	expires_at timestamp NULL,
	original_price numeric(22, 2) NULL,
	eligible int2 NULL,
	catalog_product_name varchar NULL,
	variations jsonb NULL,
	item_relations jsonb NULL,
	sku varchar NULL,
	shipping_tags jsonb NULL,
	moderation_date timestamp NULL,
	logistic_type varchar NULL,
	pictures jsonb NULL,
	description text NULL,
	"attributes" jsonb NULL,
	CONSTRAINT mshops_advertisings_pkey PRIMARY KEY (id),
	CONSTRAINT mshops_unique_external_id UNIQUE (external_id)
);

CREATE INDEX mshops_advertisings_account_id_idx ON meuml.mshops_advertisings USING btree (account_id);


ALTER TABLE meuml.mshops_advertisings ADD CONSTRAINT mshops_advertisings_account_id_fkey FOREIGN KEY (account_id) REFERENCES meuml.accounts(id);

