export default ({ documentType }) => {
  let inputList = [
    {
      col: { xs: 12, sm: 6, md: 6 },
      id: "razao_social",
      icon: "contact",
      type: "text",
      label: documentType === "cpf" ? "Nome" : "Razão Social",
      name: "razao_social",
      placeholder: documentType === "cpf" ? "Nome completo" : "Razão Social",
    },
    {
      col: { xs: 12, sm: 6, md: 6 },
      id: "email",
      icon: "contact",
      type: "text",
      label: "Email",
      name: "email",
      placeholder: "exemplo@meuml.com",
    },
    {
      col: { xs: 12, sm: 6, md: 6 },
      id: "cpf_cnpj",
      name: "cpf_cnpj",
      icon: "contact",
      type: "text",
      label: documentType === "cpf" ? "CPF" : "CNPJ",
      placeholder: "Digite somente números",
      mask: documentType === "cpf" ? "999.999.999-99" : "99.999.999/9999-99",
    },
    {
      col: { xs: 12, sm: 6, md: 6 },
      id: "cep",
      icon: "caret-right",
      type: "text",
      label: "CEP",
      name: "cep",
      placeholder: "Digite apenas números",
      mask: "99999-999",
    },
    {
      col: { xs: 12, sm: 8, md: 8 },
      id: "logradouro",
      icon: "house",
      type: "text",
      label: "Endereço",
      name: "logradouro",
      placeholder: "Ex: Av. Sete de Setembro",
    },
    {
      col: { xs: 12, sm: 4, md: 4 },
      type: "text",
      label: "Número residencial",
      name: "numero",
      id: "numero",
      placeholder: "Número residencial",
      icon: "location-pin",
    },
    {
      col: { xs: 12, sm: 6, md: 6 },
      type: "text",
      label: "Complemento de endereço",
      name: "complemento",
      id: "complemento",
      placeholder: "Ex: ap 01 bl 02",
      icon: "building",
    },
    {
      col: { xs: 12, sm: 6, md: 6 },
      type: "text",
      label: "Bairro",
      name: "bairro",
      id: "bairro",
      placeholder: "Bairro",
      icon: "caret-right",
    },
  ];
  const inscricaoEstadualInput = {
    col: { xs: 12, sm: 6, md: 6 },
    id: "inscricao_municipal",
    icon: "caret-right",
    type: "text",
    label: "Inscrição Municipal",
    name: "inscricao_municipal",
    placeholder: "Digite apenas números",
  };
  if (documentType === "cnpj") inputList.push(inscricaoEstadualInput);
  return [...inputList];
};
