const SET_PAYER_DATA                = "SET_PAYER_DATA";
const SET_USER_DATA_HISTORY         = "SET_USER_DATA_HISTORY";
const SET_IS_LOADING                = "SET_IS_LOADING";
const SET_IS_LOADING_PAYER_INFO     = "SET_IS_LOADING_PAYER_INFO";
const SET_CURRENT_USER_FORM_TAB     = "SET_CURRENT_USER_DATA_FORM_TAB";
const SET_USER_NAME                 = "SET_USER_NAME";
const SET_USER_EMAIL                = "SET_USER_EMAIL";
const SET_USER_CPF_CNPJ             = "SET_USER_CPF_CNPJ";
const SET_USER_INSCRICAO_MUNICIPAL  = "SET_USER_INSCRICAO_MUNICIPAL";
const SET_USER_ZIP_CODE             = "SET_USER_ZIP_CODE";
const SET_USER_ADDRESS_STREET       = "SET_USER_ADDRESS_STREET";
const SET_USER_ADDRESS_NUMBER       = "SET_USER_ADDRESS_NUMBER";
const SET_USER_ADDRESS_DISTRICT     = "SET_USER_ADDRESS_DISTRICT";
const SET_USER_ADDRESS_COMPLEMENT   = "SET_USER_ADDRESS_COMPLEMENT";
const SET_USER_ADDRESS_CITY         = "SET_USER_ADDRESS_CITY";
const SET_USER_ADDRESS_CITY_CODE    = "SET_USER_ADDRESS_CITY_CODE";
const SET_USER_ADDRESS_PROVINCE     = "SET_USER_ADDRESS_PROVINCE";
const SET_SHOW_DISCLAIMER_MODAL     = "SET_SHOW_DISCLAIMER_MODAL";
const SET_SHOW_USER_DATA_FORM_MODAL = "SET_SHOW_USER_DATA_FORM_MODAL";
const SET_SHOW_PAYMENT_REVIEW_MODAL = "SET_SHOW_PAYMENT_REVIEW_MODAL";
const SET_PAYMENT_CHECKOUT          = "SET_PAYMENT_CHECKOUT";
const SET_SHOW_PIX_MODAL            = "SET_SHOW_PIX_MODAL";


export {
  SET_PAYER_DATA,
  SET_IS_LOADING,
  SET_IS_LOADING_PAYER_INFO,
  SET_USER_NAME,
  SET_USER_EMAIL,
  SET_USER_CPF_CNPJ,
  SET_USER_ZIP_CODE,
  SET_USER_ADDRESS_STREET,
  SET_USER_ADDRESS_NUMBER,
  SET_USER_ADDRESS_DISTRICT,
  SET_USER_ADDRESS_COMPLEMENT,
  SET_SHOW_DISCLAIMER_MODAL,
  SET_SHOW_USER_DATA_FORM_MODAL,
  SET_USER_INSCRICAO_MUNICIPAL,
  SET_PAYMENT_CHECKOUT,
  SET_SHOW_PAYMENT_REVIEW_MODAL,
  SET_SHOW_PIX_MODAL,
  SET_USER_DATA_HISTORY,
  SET_CURRENT_USER_FORM_TAB,
  SET_USER_ADDRESS_CITY,
  SET_USER_ADDRESS_CITY_CODE,
  SET_USER_ADDRESS_PROVINCE
}